### ISSUE TITLE
Ready for TLS 1.2?

### ISSUE THREAD

**Issue by gissel-serrala** [ka4ok85/watson-campaign-automation-spring#3]
On February 10, 2020, Acoustic Campaign will remove support for TLS 1.0 and 1.1. This change will impact the communication between HCL Campaign and Acoustic.

**Is this library ready for TLS 1.2?**

**Comment by ka4ok85** [comment]
TLS restriction has no effect on library but rather on your host/server configuration. In other words if your host/server supports TLS 1.2 then library will work as usual. If not then neither library neither other approach will not work.

I am actively monitoring TLS change so I will keep this issue open until next week just to be safe.

Thanks for your support.

**Comment by ka4ok85** [comment]
TLS update did not cause any issues.
