### ISSUE TITLE
Change URLs to match new Acoustic URLs

### ISSUE THREAD

**Issue by gissel-serrala** [ka4ok85/watson-campaign-automation-spring#4]
The transition from IBM to Acoustic does also concern this project. Basically all URLs will change until end of June. They already made the new URLs available and reachable.

https://acoustic.com/standardized-acoustic-urls/

**Comment by ka4ok85** [comment]
Thanks for heads up! Lib relies on old Silverpop URLs that will be available at least through the end of 2020. "Updated" URLs driven by acquisitions were changed twice already but "native" are remaining the same. I think they will be available after 2020. I am closing this issue for now but I will keep an eye on potential issues next year.

p.s. could you please send me quick email to makovetsky.evgeny@gmail.com? I have a question regarding your experience with lib.
